# Makefile.dep created Sun Feb  1 17:20:22 PST 2015
bigint.o: bigint.cpp bigint.h debug.h util.h
scanner.o: scanner.cpp scanner.h debug.h
debug.o: debug.cpp debug.h util.h
util.o: util.cpp util.h debug.h
main.o: main.cpp bigint.h debug.h iterstack.h scanner.h util.h
